// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1653926238);
user_pref("app.update.lastUpdateTime.region-update-timer", 1653926478);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1654523206);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1653926118);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1653926027);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1653926358);
user_pref("browser.region.update.updated", 1653925972);
user_pref("browser.search.region", "KE");
user_pref("browser.theme.dark-toolbar-theme", false);
user_pref("calendar.timezone.local", "Africa/Nairobi");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1653925980097");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.cache.lastUpdate", 1653926238);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20220520005021");
user_pref("extensions.lastAppVersion", "91.9.1");
user_pref("extensions.lastPlatformVersion", "91.9.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"e7691ad8-4f4b-40bb-a0ba-d257f707b1b0\",\"google@search.mozilla.org\":\"7d4d570e-b1c7-44c9-af6f-788f68c534e2\",\"ddg@search.mozilla.org\":\"5b8ee7f6-4163-47d2-bb72-d3888d4f808e\",\"amazondotcom@search.mozilla.org\":\"0916e132-f91d-4690-8848-428674754673\",\"wikipedia@search.mozilla.org\":\"998edac8-b7b6-4f82-884a-b38db9747997\",\"bing@search.mozilla.org\":\"457366f2-1874-47c4-a0b7-28cb23b7cbea\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.root.imap", "/home/victorious/.thunderbird/ib2wpb39.default-release/ImapMail");
user_pref("mail.root.imap-rel", "[ProfD]ImapMail");
user_pref("mail.ui-rdf.version", 32);
user_pref("mailnews.database.global.datastore.id", "c0fd9600-9995-48e7-9f00-7c56a42d8d4");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "91.9.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("services.settings.clock_skew_seconds", -13828);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1653939945);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1653939945);
user_pref("services.settings.thunderbird.search-config.last_check", 1653939945);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1653939945);
user_pref("toolkit.telemetry.cachedClientID", "af39807b-0f51-4f15-b766-71ca3b23b2b5");
user_pref("toolkit.telemetry.previousBuildID", "20220520005021");
